/* ================= TAIL NUMBERS ================= */
const tailNumbers = {
  "A350-1000": ["ET-BAY", "ET-BAX", "ET-BAW"],
  "A350-900": ["ET-ATQ", "ET-ATR", "ET-ATY", "ET-AUA", "ET-AUB", "ET-AUC", "ET-AVB", "ET-AVC", "ET-AVD", "ET-AVE", "ET-AWM", "ET-AWN", "ET-AWO", "ET-AWP", "ET-AYA", "ET-AYB", "ET-AYM", "ET-AYN", "ET-AZI", "ET-AZN"],
  "B737-700": ["ET-ALM", "ET-ALN"],
  "B737-MAX": ["ET-AVI", "ET-AVK", "ET-AVL", "ET-AVM", "ET-AWF", "ET-AWG", "ET-AWH", "ET-AWI", "ET-AWJ", "ET-AWK", "ET-AXG", "ET-AZA", "ET-AZO", "ET-BAI", "ET-BAK", "ET-BAL", "ET-BAN", "ET-BAO", "ET-BAT", "ET-BBA"],
  "B767-300": ["ET-BBE", "ET-BBF"],
  "B777-200": ["ET-ANN", "ET-ANO", "ET-ANP", "ET-ANQ", "ET-ANR", "ET-APS", "ET-APU", "ET-APX", "ET-APY", "ET-AQL", "ET-ARH", "ET-ARI", "ET-ARJ", "ET-ARK", "ET-ASK", "ET-ASL", "ET-AVN", "ET-AVQ", "ET-AVT", "ET-AWE", "ET-BAA", "ET-BAB", "ET-BBG"],
  "B787-800": ["ET-AOO", "ET-AOP", "ET-AOQ", "ET-AOR", "ET-AOS", "ET-AOT", "ET-AOU", "ET-AOV", "ET-ARE", "ET-ARF", "ET-ASG", "ET-ASH", "ET-ASI", "ET-ATG", "ET-ATH", "ET-ATI", "ET-ATJ", "ET-ATK", "ET-ATL", "ET-AUO", "ET-AUP", "ET-AUQ", "ET-AUR", "ET-AXK", "ET-AXL", "ET-AXS", "ET-AXT", "ET-AYC", "ET-AYD"],
  "Q400": ["ET-ANI", "ET-ANJ", "ET-ANK", "ET-ANL", "ET-ANV", "ET-ANX", "ET-ANY", "ET-AQB", "ET-AQC", "ET-AQD", "ET-AQE", "ET-AQF", "ET-ARL", "ET-ARM", "ET-ARN", "ET-ASA", "ET-AUD", "ET-AUE", "ET-AUZ", "ET-AVA", "ET-AVH", "ET-AVR", "ET-AVS", "ET-AXE", "ET-AXF", "ET-AXP", "ET-AXW", "ET-AXX", "ET-AXY", "ET-AXZ", "ET-AYF", "ET-AYG", "ET-AYH"]
};

/* ================= AIRPORTS ================= */
const airports = [
  "ABIDJAN (ABJ)(DIAP)", "ABUJA (ABV)(DNAA)", "ACCRA (ACC)(DGAA)", "ADDIS ABABA (ADD)(HAAB)",
  "ALGIERS (ALG)(DAAG)", "AL-MAKTOUM INTERNATIONAL (DWC)(OMDW)", "ANCHORAGE AK (ANC)(PANC)",
  "ANTANANARIVO (TNR)(FMMI)", "ARBA MINTCH (AMH)(HAAM)", "ASMARA (ASM)(HHAS)", "ASOSA (ASO)(HASO)",
  "ATHENS (ATH)(LGAV)", "Axum (AXU)(HAAX)", "BAHAR DAR (BJR)(HABD)", "Bahrain Airport (BAH)(OBBI)",
  "BAMAKO (BKO)(GABS)", "BANGALORE (KARNATAKA) (BLR)(VOBL)", "BANGKOK (BKK)(VTBS)",
  "BANGUI (BGF)(FEFF)", "BANJUL (BJL)(GBYD)", "Barajas Airport (MAD)(LEMD)", "BEIJING CAPITAL AIRPORT (PEK)(ZBAA)",
  "BEIRA (BEW)(FQBR)", "BEIRUT (BEY)(OLBA)", "BISSAU (OXB)(GGOV)", "BLANTYRE (BLZ)(FWCL)",
  "BOGOTA (BOG)(SKBO)", "BOMBAY (MAH) (BOM)", "BOSSASO (BSA)(HCMF)", "BRAZZAVILLE (BZV)(FCBB)",
  "BRUSSELS (BRU)(EBBR)", "BUJUMBURA (BJM)(HBBA)", "Bulawayo (BUQ)(FVJN)", "CAIRO (CAI)(HECA)",
  "CAPE TOWN (CPT)(FACT)", "CHARLES DE GAULLE AIRPORT (CDG)(LFPG)", "CHENGDU (CTU)(ZUUU)",
  "CHENNAI (TN) (MAA)(VOMM)", "CHICAGO O'HARE INTL IL (ORD)(KORD)", "COLOGNE (CGN)(EDDK)",
  "CONAKRY (CKY)(GUCY)", "Copenhagen (CPH)(EKCH)", "COTONOU (COO)(DBBB)", "DAKAR (DSS)(GOBD)",
  "DALLAS /FT.WORTH INTL. APT. TX (DFW)(KDFW)", "Dammam Airport (DMM)(OEDF)", "DAR ES SALAAM (DAR)(HABD)",
  "DELHI (DEL) (VIDP)", "DEMBIDOLLO (DEM)(HADD)", "DESSIE (DSE)(HADC)", "DHAKA (DAC)(VGHS)",
  "DIRE DAWA (DIR)(HADR)", "DJIBOUTI (JIB)(HDAM)", "DOHA (DOH)(OTHH)", "DOMODEDOVO (DME)(UUDD)",
  "DOUALA (DLA)(FKKD)", "DUBAI (DXB)(OMDB)", "DUBLIN (DUB)(EIDW)", "ELDORET (EDL)(HKEL)",
  "ENTEBBE (EBB)(HUEN)", "Enugu (ENU)(DNEN)", "Ezhou Huahu Airport (EHU)(ZHEC)", "FRANKFURT (FRA)(EDDF)",
  "FREETOWN /LUNGI INTL. APT. (FNA)(GFLL)", "GABORONE (GBE)(FBSK)", "GAMBELA (GMB)(HAGM)", "GAROE (GGR)(HCGR)",
  "GAROUA (GOU)(FKKR)", "GATWICK(LGW)(EGKK)", "GENEVA (GVA)(LSGG)", "GOBA (GOB)(HAGB)",
  "GODE (GDE)(HAGO)", "GOMA (GOM)(FZNA)", "GONDAR (GDQ)(HAGN)", "GUANGZHOU (CAN)(ZGGG)",
  "GUARULHOS INTL AIRPORT (GRU)(SBGR)", "HAHAYA AEROPORT INTL. COMORES (HAH)(FMCH)", "HANOI (HAN)(VVNB)",
  "HARARE (HRE)(FVRG)", "HARGEISA (HGA)(HCMH)", "Hartsfield-Jackson Atlanta International Airport (ATL)(KATL)",
  "HAWASA (AWA)(HALA)", "HEYDAR ALIYEV INTER. AIRPORT (GYD)(UBBB)", "HONG KONG (HKG)(VHHH)", "HYDERABAD (AP) (HYD)(VOHS)",
  "INCHEON INTL AIRPORT (ICN)(RKSI)", "ISTANBUL (IST)(LTFM)", "J F KENNEDY INT. AIRPORT (JFK)(KJFK)", "JAKARTA SOEKARNO-HATTA AIRPORT (CGK)(WIII)",
  "JEDDAH (JED)(OEJN)", "JIMMA (JIM)(HAJM)", "JINKA (BCO)(HABC)", "JOHANNESBURG (JNB)(FAOR)", "JUBA (JUB)(HJJJ)",
  "KANO (KAN)(DNKN)", "Kassala Airport (KSL)(HSKA)", "KHARTOUM (KRT)(HSSK)", "KIGALI (KGL)(HRYR)", "KILIMANJARO (JRO)(HTKJ)",
  "KING MSWATI (SHO)(FDSK)", "KINSHASA (FIH)(FZAA)", "KUALA LUMPUR (KUL)(WMKK)", "KUWAIT (KWI)(OKKK)", "LAGOS (LOS)(DNMM)",
  "LALIBELA (LLI)(HALL)", "LEONARDO DA VINCI AIRPORT (FCO)(LIRF)", "LIBREVILLE (LBV)(FOOL)", "LIEGE (LGG)(EBLG)",
  "LILONGWE (LLW)(FWKI)", "LOME (LFW)(DXXX)", "LONDON HEATHROW AIRPORT (LHR)(EGLL)", "LOS ANGELES CA (LAX)(KLAX)",
  "LUANDA (LAD)(FNLU)", "LUBUMBASHI (FBM)(FZQA)", "LUSAKA (LUN)(FLKK)", "MAASTRICHT (MST)(EHBK)", "MAHE ISLAND (SEZ)(FSIA)",
  "MALABO (SSG)(FGSL)", "MALPENSA AIRPORT (MXP)(LIMC)", "MANCHESTER (MAN)(EGCC)", "MANILA (MNL)(RPLL)",
  "MAPUTO (MPM)(FQMA)", "MARSICAL SUCRE (UIO)(SEQM)", "MARSEILLE (MRS)(LFML)", "MASERU (MSU)(FXMM)", "Maun Airport (MUB)(FBMN)",
  "MAURITIUS (MRU)(FIMP)", "Medina Airport (MED)(OEMA)", "Mekelle (MQX)(HAMK)", "MEXICO CITY (MEX)(MMMX)", "MIAMI. FL (MIA)(KMIA)",
  "MINISTRO PISTARINI AR (EZE)(SAEZ)", "Minna Airport(MXJ)(DNMN)", "MOGADISHU (MGQ)(HCMM)", "MOMBASA (MBA)(HKMO)",
  "MUSCAT (MCT)(OOMS)", "NAIROBI/JOMO KENYATTA INTL.APT (NBO)(HKJK)", "NARITA AIRPORT (NRT)(RJAA)", "NDJAMENA (NDJ)(FTTJ)",
  "NDOLA (NLA)(FLSK)", "Nekemte (NEK)(HANK)", "NEWARK NJ (EWR)(KEWR)", "NIAMEY (NIM)(DRRN)", "NOSSI BE (NOS)(FMNN)",
  "NOUAKCHOTT (NKC)(GQNO)", "NSIMALEN (NSI)(FKYS)", "Nursultan Nazarbayev(NQZ)(UACC)", "OSLO (OSL)(ENGM)",
  "OUAGADOUGOU (OUA)(DFFD)", "PHILADELPHIA PA/CAMDEN NJ (PHL)(KPHL)", "POINTE NOIRE (PNR)(FCPP)",
  "Port Sudan new International Airport (PZU)(HSPN)", "PRAIA (RAI)(GVNP)", "PUDONG - SHANGHAI (PVG)(ZSPD)",
  "Queen Alia International Airport (AMM)(OJAI)", "RABAT (RBA)(GMME)", "RAMSTEIN (RMS)(ETAR)", "RIYADH (RUH)(OERK)",
  "ROBERTS INTERNATIONAL (ROB)(GLRB)", "SANTIAGO (SCL)(SCEL)", "SEMERA (SZE)(HASM)", "SHARJAH (SHJ)(OMSJ)",
  "Shire (SHC)(HASR)", "SINGAPORE (SIN)(WSSS)", "STOCKHOLM (ARN)(ESSA)", "TAIYUAN (TYN)(ZBYN)", "TEKIRDAG (TEQ)(LTBU)",
  "TEL AVIV YAFO (TLV)(LLBG)", "TORONTO PEARSON INTL. APT. (YYZ)(CYYZ)", "TUNIS (TUN)(DTTA)", "URUMQI (URC)(ZWWW)",
  "VICTORIA FALLS (VFA)(FVFA)", "VIENNA (VIE)(LOWW)", "Warsaw Chopin (WAW)(EPWA)", "WASHINGTON DULLES INTL.APT. (IAD)(KIAD)",
  "WINDHOEK (WDH)(FYWH)", "WUHAN (WUH)(ZHHH)", "ZANZIBAR (ZNZ)(HTZA)", "ZARAGOZA (ZAZ)(LEZG)", "ZHENGZHOU (CGO)(ZHCC)"
];

/* ================= SPI OPTIONS ================= */
const spiOptions = [
  "Un-stabilized approach",
  "Hard landing",
  "Deep landing",
  "Non-compliance with ATC instruction",
  "Runway excursion/incursion",
  "Taxiway excursion/incursion",
  "Tail strike",
];

/* ================= FLIGHT PHASE OPTIONS ================= */
const flightPhaseOptionsList = [
  "Approach Descent",
  "Circling",
  "Climb to cruise",
  "Cruise",
  "Engine Run-up",
  "Enroute",
  "Final Approach",
  "Flare/Touch down",
  "Gate arrival- (Power-in/Tow-in)",
  "Go-around",
  "Ground Servicing/Towing",
  "Hangar maintenance",
  "Holding any level",
  "Initial Approach",
  "Initial Climb",
  "Landing roll",
  "Loading/Boarding",
  "Missed approach",
  "Post-flight",
  "Pre-flight",
  "Push-back roll-out",
  "Repositioning",
  "Starting Engines",
  "Take-off roll",
  "Takeoff queue",
  "Taxi to from runway/Arrival",
  "Taxi to from runway/Departure",
  "Unknown",
  "Unloading/De-planing"
];
export { tailNumbers, airports, spiOptions, flightPhaseOptionsList };
