FROM node:20-alpine
WORKDIR /app

# Copy backend dependencies
COPY package*.json ./
RUN npm install --production

# Copy backend code
COPY . .

# Create directory for frontend (will be mounted via volume)
RUN mkdir -p /app/front/dist

EXPOSE 4000
CMD ["node", "server.js"]