FROM node:18-alpine

# Install build tools for native modules
RUN apk add --no-cache python3 make g++

WORKDIR /app

ENV NODE_TLS_REJECT_UNAUTHORIZED=0

RUN npm config set strict-ssl false && \
    npm config set registry http://registry.npmjs.org/

COPY package*.json ./
RUN npm install --production

COPY . .

EXPOSE 4000
CMD ["node", "server.js"]