server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;   # fixes React Router refresh 404
    }

    # Forward API calls to backend
    location /api/ {
        proxy_pass http://office_backend:4000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_cache_bypass $http_upgrade;
    }

    # Forward uploads to backend
    location /uploads/ {
        proxy_pass http://office_backend:4000;
        proxy_set_header Host $host;
    }
}